### ISSUE TITLE
ImportError: No module named browser_service

### ISSUE THREAD

**Issue by ldevalbray** [JarbasAl/browser_service#1]
Hello, I'm trying to user browser_service but it does not seem to find it.

I am importing it like that in my __init__.py file

```
import sys
from os.path import dirname, abspath, basename

sys.path.append(dirname(dirname(__file__)))

from browser_service import BrowserControl
```

Moreover, I wonder if you have any way to add an `.execute_script()` and `actions chains` methods to the browser ? (As in Selenium) It does not seem to have any of those two :)

Thank you for your help

**Comment by JarbasAl** [comment]
https://github.com/JarbasAl/browser_service/wiki/making-a-selenium-skill

refactored to use my utils package, closing this for now

i will be making a wiki page on how to add extra selenium functionality
